export enum ActionTypes {
	SIGN_IN = 'SIGN_IN',
	SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',

	SIGN_UP = 'SIGN_UP',
	SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',

	SIGN_OUT = 'SIGN_OUT',
	SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS',

	CHECK_AUTH = 'CHECK_AUTH',
	CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS',

	AUTH_ERROR = 'AUTH_ERROR',
	CLEAR_ERROR = 'CLEAR_ERROR',

	GET_IMAGES = 'GET_IMAGES',
	GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS',
	SET_IMAGES = 'SET_IMAGES',

	SAVE_IMAGE = 'SAVE_IMAGE',

	SET_TOOL = 'SET_TOOL',
	SET_LINE_WIDTH = 'SET_LINE_WIDTH',
	SET_LINE_COLOR = 'SET_LINE_COLOR',
	SET_LINE_OPACITY = 'SET_LINE_OPACITY',

	RESET_CANVAS = 'RESET_CANVAS',

	IMAGES_FILTER = 'IMAGES_FILTER',
}
