export enum ActionTypes {
	SIGN_IN = 'SIGN_IN',
	SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
	SIGN_IN_ERROR = 'SIGN_IN_ERROR',

	SIGN_UP = 'SIGN_UP',
	SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',

	SIGN_OUT = 'SIGN_OUT',

	GET_IMAGES = 'GET_IMAGES',
}
